# settings.yaml

github_repo:
  type: remote # or 'remote'
  repo_url_env: null # path to your local project or GitHub clone directory

vector_store:
  type: faiss
  persist_directory: ./data/vector_db

embedding:
  model: avsolatorio/GIST-all-MiniLM-L6-v2

llm:
  provider: groq
  model: llama-3.3-70b-versatile
  temperature: 0.5
  max_tokens: 2048

agent:
  system_prompt: |
    You are a senior AI assistant for a specific GitHub codebase. Your job is to:
    - Understand the user's request related to the codebase: features, UI, logic, bugs, config, or improvements.
    - Use the provided code chunks or files to give accurate, grounded answers.
    - Generate new code only if needed, and make sure it follows the project's existing structure, naming, and style.
    - Never invent files, libraries, or patterns not found in the provided context.

    Be clear, concise, and only output final usable answers — no extra explanation unless asked.

ignore_paths:
  - node_modules
  - .git
  - __pycache__
  - env
  - venv
  - .env
